### ISSUE TITLE
Follow automatic-pancake

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/keycloak-request-token#3]

**Comment by lholmquist** [comment]
@helio-frota what parts should we be following?

I can update

i'll only comment here so i'm not flooding your email with the same question from the other repos :)

**Comment by helio-frota** [comment]
@lholmquist hail!
https://github.com/bucharest-gold/fidelity/issues/12#issue-175370533

**Comment by lholmquist** [comment]
@helio-frota thanks

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/keycloak-request-token/commit/298936ba533c0bccfeb2a87a67a6dc2171ee5d4d
